name: Make a Pyinstall Runner

on:
  push:
    branches: [ '**' ]

jobs:
  build_pyinstall:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
         include:
           - os: ubuntu-latest
             extension: ""
           - os: macos-latest
             extension: ""
           - os: windows-latest
             extension: ".exe"

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"
          cache: "pip"

      - name: Build and Install
        run: |
          python -m pip install --upgrade pip setuptools
          python -m pip install pyinstaller
          pyinstaller hello_world.py

      - uses: actions/upload-artifact@v6
        with:
          name: hello_world${{ matrix.extension }}
          path: dist/hello_world
